services:
  twochi-api:
    build:
      context: .
      target: test
    command: ["sh", "-c", "sleep 5 && gleam run"]
    container_name: twochi-api
    stop_signal: sigkill
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      PORT: 8000
      DB_URI: "postgresql://root@postgres:5432/bot"
      DB_PASS: "password"
    develop:
      watch:
        - action: rebuild
          path: .

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
