name = "twochi_api"
version = "1.0.0"

[dependencies]
gleam_stdlib = "== 0.55.0"
gleam_erlang = "== 0.34.0"
mist = "== 4.0.6"
wisp = "== 1.5.3"
glenvy = "== 1.2.0"
gleam_json = "== 2.3.0"
gleam_http = "== 4.0.0"
given = "== 5.0.2"
mungo = "== 0.27.0"
bison = "== 1.7.0"

[dev-dependencies]
gleeunit = "== 1.3.0"
