name = "twochi_api"
version = "1.0.0"

[dependencies]
gleam_stdlib = "== 0.59.0"
gleam_erlang = "== 0.34.0"
mist = "== 4.0.7"
wisp = "== 1.7.0"
gleam_json = "== 3.0.1"
gleam_http = "== 4.0.0"
given = "== 5.0.4"
envoy = "== 1.0.2"
sqlight = ">= 1.0.1 and < 2.0.0"
pog = ">= 3.2.0 and < 4.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "== 1.3.1"
